### ISSUE TITLE
Drag and Drop reordering

### ISSUE THREAD

**Issue by ghost** [jarnix/bashrcgenerator#1]
Hey it would be nice if we could reorder elements once we have selected them. :)

**Comment by jarnix** [comment]
Actually you can reorder :) It's strange that you cannot reorder. I know that there is something strange in the behavior but you can do it. I tried with FF and Chrome.

What is your browser and OS so I can try and reproduce the issue ?

**Comment by ghost** [comment]
I tried it on FF 37.0.2 on a 64bit Ubuntu 14.10 (Unity).

Hey it's working now! Earlier I hadn't waited long enough for the placeholder to appear. Thanks :)

**Comment by jarnix** [comment]
Hi,

I fixed the strange drag and drop issues. It's really faster and smoother now.

Julien

**Comment by ghost** [comment]
Hi Julien,

It's much more responsive now. Awesome app! Easy even for a newbie :)

Thanks,
Kenny.
